/*
 * SPDX-License-Identifier: BSD-3-Clause-Clear
 *
 * Auto-generated by riscv-unified-db (udb-gen cfg-c-header)
 * Config: MC100-32-Full
 *
 * Define conventions:
 *   Boolean params:       #define NAME           (present when true, absent when false)
 *   Integer params:       #define NAME value
 *   Enum (string) params: #define NAME_VALUE     (value sanitized to uppercase identifier)
 *   Boolean arrays:       #define NAME_<index>   (one per true element)
 *   Integer arrays:       #define NAME_<value>   (one per unique element, sorted)
 *   String arrays:        #define NAME_<VALUE>   (one per unique element, sanitized)
 */

#ifndef UDB_CFG_MC100_32_FULL_H
#define UDB_CFG_MC100_32_FULL_H

/* Derived ISA widths */
#define XLEN32

/* Implemented extensions */
#define C_SUPPORTED
#define I_SUPPORTED
#define M_SUPPORTED
#define SM_SUPPORTED
#define SMRNMI_SUPPORTED
#define ZCA_SUPPORTED
#define ZICNTR_SUPPORTED
#define ZICSR_SUPPORTED

/* Configuration parameters */
#define ARCH_ID_VALUE 1
#define IMP_ID_VALUE 0
#define MARCHID_IMPLEMENTED
#define MIMPID_IMPLEMENTED
#define MISALIGNED_LDST
#define MISALIGNED_LDST_EXCEPTION_PRIORITY_LOW
#define MISALIGNED_MAX_ATOMICITY_GRANULE_SIZE 4
#define MISALIGNED_SPLIT_STRATEGY_SEQUENTIAL_BYTES
#define MISA_CSR_IMPLEMENTED
#define MTVAL_WIDTH 32
#define MTVEC_ACCESS_RW
#define MTVEC_BASE_ALIGNMENT_DIRECT 4
#define MTVEC_BASE_ALIGNMENT_VECTORED 4
#define MTVEC_ILLEGAL_WRITE_BEHAVIOR_RETAIN
#define MTVEC_MODES_0
#define MTVEC_MODES_1
#define MXLEN 32
#define M_MODE_ENDIANNESS_LITTLE
#define NUM_PMP_ENTRIES 0
#define PHYS_ADDR_WIDTH 32
#define PMA_GRANULARITY 12
#define PRECISE_SYNCHRONOUS_EXCEPTIONS
#define REPORT_ENCODING_IN_MTVAL_ON_ILLEGAL_INSTRUCTION
#define REPORT_VA_IN_MTVAL_ON_BREAKPOINT
#define REPORT_VA_IN_MTVAL_ON_INSTRUCTION_ACCESS_FAULT
#define REPORT_VA_IN_MTVAL_ON_INSTRUCTION_MISALIGNED
#define REPORT_VA_IN_MTVAL_ON_LOAD_ACCESS_FAULT
#define REPORT_VA_IN_MTVAL_ON_LOAD_MISALIGNED
#define REPORT_VA_IN_MTVAL_ON_STORE_AMO_ACCESS_FAULT
#define REPORT_VA_IN_MTVAL_ON_STORE_AMO_MISALIGNED
#define TRAP_ON_EBREAK
#define TRAP_ON_ECALL_FROM_M
#define TRAP_ON_ILLEGAL_WLRL
#define TRAP_ON_RESERVED_INSTRUCTION
#define TRAP_ON_UNIMPLEMENTED_CSR
#define TRAP_ON_UNIMPLEMENTED_INSTRUCTION
#define VENDOR_ID_BANK 1
#define VENDOR_ID_OFFSET 1

#endif /* UDB_CFG_MC100_32_FULL_H */
