# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# typed: true
# frozen_string_literal: true

require "fileutils"
require "pathname"
require "sorbet-runtime"
require "tty-exit"

require_relative "../../common_opts"
require_relative "../../defines"

require "udb/obj/extension"

module UdbGen
  class GenCfgSvhHeaderOptions < SubcommandWithCommonOptions
    include TTY::Exit

    NAME = "cfg-svh-header"

    sig { void }
    def initialize
      super(name: NAME, desc: "Generate a SystemVerilog header with `defines from a fully configured UDB config")
    end

    usage \
      command: NAME,
      desc: "Generate a SystemVerilog header file with `define directives derived from a fully configured UDB YAML config",
      example: <<~EXAMPLE
        Generate a SystemVerilog header for the rv64 config, printed to stdout
          $ #{File.basename($PROGRAM_NAME)} #{NAME} -c rv64

        Generate a SystemVerilog header for the rv64 config, written to a file
          $ #{File.basename($PROGRAM_NAME)} #{NAME} -c rv64 -o config.svh

        Generate a SystemVerilog header for a custom config file
          $ #{File.basename($PROGRAM_NAME)} #{NAME} -c /path/to/my_config.yaml
      EXAMPLE

    option :output do
      T.bind(self, TTY::Option::Parameter::Option)
      short "-o"
      long "--output=file"
      desc "Output file path (default: stdout)"
      convert :path
    end

    sig { returns(String) }
    def generate_header
      unless cfg_arch.fully_configured?
        exit_with(:data_err, "Config '#{cfg_arch.name}' is not fully configured. Only fully configured configs are supported.\n")
      end

      lines = []
      guard_name = "UDB_CFG_#{cfg_arch.name.upcase.gsub(/[^A-Z0-9]/, "_")}_SVH"

      lines << "// SPDX-License-Identifier: BSD-3-Clause-Clear"
      lines << "//"
      lines << "// Auto-generated by riscv-unified-db (udb-gen #{NAME})"
      lines << "// Config: #{cfg_arch.name}"
      lines << "//"
      lines << "// Define conventions:"
      lines << "//   Boolean params:       `define NAME           (present when true, absent when false)"
      lines << "//   Integer params:       `define NAME value"
      lines << "//   Enum (string) params: `define NAME_VALUE     (value sanitized to uppercase identifier)"
      lines << "//   Boolean arrays:       `define NAME_<index>   (one per true element)"
      lines << "//   Integer arrays:       `define NAME_<value>   (one per element)"
      lines << "//   String arrays:        `define NAME_<VALUE>   (one per element, sanitized)"
      lines << ""
      lines << "`ifndef #{guard_name}"
      lines << "`define #{guard_name}"

      lines << ""
      lines << "// Derived ISA widths"
      emit_width_defines(lines)

      lines << ""
      lines << "// Implemented extensions"
      emit_extension_defines(lines)

      lines << ""
      lines << "// Configuration parameters"
      emit_param_defines(lines)

      lines << ""
      lines << "`endif // #{guard_name}"
      lines << ""

      lines.join("\n")
    end

    sig { override.params(argv: T::Array[String]).returns(T.noreturn) }
    def run(argv)
      parse(argv)

      if params[:help]
        print help
        exit_with(:success)
      end

      if params.errors.any?
        exit_with(:usage_error, "#{params.errors.summary}\n\n#{help}")
      end

      unless params.remaining.empty?
        exit_with(:usage_error, "Unknown arguments: #{params.remaining}\n")
      end

      header = generate_header

      if params[:output].nil?
        $stdout.puts header
      else
        FileUtils.mkdir_p(params[:output].dirname)
        File.write(params[:output], header)
        Udb.logger.info "Generated SystemVerilog header: #{params[:output]}"
      end

      exit_with(:success)
    end

    private

    sig { params(str: String).returns(String) }
    def sanitize_to_identifier(str)
      str.upcase.gsub(/[^A-Z0-9]/, "_").gsub(/_+/, "_").gsub(/\A_|_\z/, "")
    end

    sig { params(lines: T::Array[String]).void }
    def emit_width_defines(lines)
      mxlen = cfg_arch.mxlen
      lines << "`define XLEN#{mxlen}" unless mxlen.nil?

      flen = derive_flen
      lines << "`define FLEN#{flen}" unless flen.nil?
    end

    sig { returns(T.nilable(Integer)) }
    def derive_flen
      if cfg_arch.ext?(:Q)
        128
      elsif cfg_arch.ext?(:D)
        64
      elsif cfg_arch.ext?(:F)
        32
      else
        nil
      end
    end

    sig { params(lines: T::Array[String]).void }
    def emit_extension_defines(lines)
      ext_names = cfg_arch.implemented_extension_versions.map(&:name).uniq.sort
      ext_names.each do |name|
        lines << "`define #{name.upcase}_SUPPORTED"
      end
    end

    sig { params(lines: T::Array[String]).void }
    def emit_param_defines(lines)
      pv = cfg_arch.param_values
      return if pv.nil? || pv.empty?

      pv.sort_by { |k, _| k }.each do |name, value|
        case value
        when true
          lines << "`define #{name}"
        when false
          next
        when Integer
          lines << "`define #{name} #{value}"
        when String
          lines << "`define #{name}_#{sanitize_to_identifier(value)}"
        when Array
          emit_array_param(lines, name, value)
        end
      end
    end

    sig { params(lines: T::Array[String], name: String, value: T::Array[T.untyped]).void }
    def emit_array_param(lines, name, value)
      if value.all? { |v| v == true || v == false }
        value.each_with_index do |v, i|
          lines << "`define #{name}_#{i}" if v
        end
      elsif value.all? { |v| v.is_a?(Integer) }
        value.each do |v|
          lines << "`define #{name}_#{v}"
        end
      elsif value.all? { |v| v.is_a?(String) }
        value.each do |v|
          lines << "`define #{name}_#{sanitize_to_identifier(v)}"
        end
      end
    end
  end
end
