# Copyright (c) Jordan Carlin, Harvey Mudd College.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# typed: true
# frozen_string_literal: true

require "fileutils"
require "pathname"
require "sorbet-runtime"
require "tty-exit"

require "udb/obj/extension"

module UdbGen
  # Shared logic for generating config header files across languages (C, SystemVerilog, etc.).
  # Including classes must define the language-specific syntax methods listed below.
  module CfgHeaderBase
    extend T::Sig
    extend T::Helpers

    interface!

    # The preprocessor define directive, e.g. "#define" or "`define"
    sig { abstract.returns(String) }
    def define_directive; end

    # The conditional guard directive, e.g. "#ifndef" or "`ifndef"
    sig { abstract.returns(String) }
    def guard_directive; end

    # The end-guard line, e.g. "#endif /* NAME */" or "`endif // NAME"
    sig { abstract.params(guard_name: String).returns(String) }
    def end_guard(guard_name); end

    # Guard name suffix, e.g. "_H" or "_SVH"
    sig { abstract.returns(String) }
    def guard_suffix; end

    # A section comment line, e.g. "/* text */" or "// text"
    sig { abstract.params(text: String).returns(String) }
    def section_comment(text); end

    # Multi-line file header comment block
    sig { abstract.params(text_lines: T::Array[String]).returns(T::Array[String]) }
    def header_comment(text_lines); end

    # Human-readable file type for log messages, e.g. "C header" or "SystemVerilog header"
    sig { abstract.returns(String) }
    def file_type_name; end

    sig { returns(String) }
    def generate_header
      unless cfg_arch.fully_configured?
        exit_with(:data_err, "Config '#{cfg_arch.name}' is not fully configured. Only fully configured configs are supported.\n")
      end

      lines = []
      guard_name = "UDB_CFG_#{cfg_arch.name.upcase.gsub(/[^A-Z0-9]/, "_")}#{guard_suffix}"

      convention_lines = [
        "SPDX-License-Identifier: BSD-3-Clause-Clear",
        "",
        "Auto-generated by riscv-unified-db (udb-gen #{self.class::NAME})",
        "Config: #{cfg_arch.name}",
        "",
        "Define conventions:",
        "  Boolean params:       #{define_directive} NAME           (present when true, absent when false)",
        "  Integer params:       #{define_directive} NAME value",
        "  Enum (string) params: #{define_directive} NAME_VALUE     (value sanitized to uppercase identifier)",
        "  Boolean arrays:       #{define_directive} NAME_<index>   (one per true element)",
        "  Integer arrays:       #{define_directive} NAME_<value>   (one per unique element, sorted)",
        "  String arrays:        #{define_directive} NAME_<VALUE>   (one per unique element, sanitized)"
      ]

      lines.concat(header_comment(convention_lines))
      lines << ""
      lines << "#{guard_directive} #{guard_name}"
      lines << "#{define_directive} #{guard_name}"

      lines << ""
      lines << section_comment("Derived ISA widths")
      emit_width_defines(lines)

      lines << ""
      lines << section_comment("Implemented extensions")
      emit_extension_defines(lines)

      lines << ""
      lines << section_comment("Configuration parameters")
      emit_param_defines(lines)

      lines << ""
      lines << end_guard(guard_name)
      lines << ""

      lines.join("\n")
    end

    sig { params(argv: T::Array[String]).returns(T.noreturn) }
    def run_generator(argv)
      parse(argv)

      if params[:help]
        print help
        exit_with(:success)
      end

      if params.errors.any?
        exit_with(:usage_error, "#{params.errors.summary}\n\n#{help}")
      end

      unless params.remaining.empty?
        exit_with(:usage_error, "Unknown arguments: #{params.remaining}\n")
      end

      header = generate_header

      if params[:output].nil?
        $stdout.puts header
      else
        FileUtils.mkdir_p(params[:output].dirname)
        File.write(params[:output], header)
        Udb.logger.info "Generated #{file_type_name}: #{params[:output]}"
      end

      exit_with(:success)
    end

    private

    sig { params(str: String).returns(String) }
    def sanitize_to_identifier(str)
      str.upcase.gsub(/[^A-Z0-9]/, "_").gsub(/_+/, "_").gsub(/\A_|_\z/, "")
    end

    sig { returns(T.nilable(Integer)) }
    def derive_flen
      if cfg_arch.ext?(:Q)
        128
      elsif cfg_arch.ext?(:D)
        64
      elsif cfg_arch.ext?(:F)
        32
      else
        nil
      end
    end

    sig { params(lines: T::Array[String]).void }
    def emit_width_defines(lines)
      mxlen = cfg_arch.mxlen
      lines << "#{define_directive} XLEN#{mxlen}" unless mxlen.nil?

      flen = derive_flen
      lines << "#{define_directive} FLEN#{flen}" unless flen.nil?
    end

    sig { params(lines: T::Array[String]).void }
    def emit_extension_defines(lines)
      ext_names = cfg_arch.implemented_extension_versions.map(&:name).uniq.sort
      ext_names.each do |name|
        lines << "#{define_directive} #{name.upcase}_SUPPORTED"
      end
    end

    sig { params(lines: T::Array[String]).void }
    def emit_param_defines(lines)
      pv = cfg_arch.param_values
      return if pv.nil? || pv.empty?

      pv.sort_by { |k, _| k }.each do |name, value|
        case value
        when true
          lines << "#{define_directive} #{name}"
        when false
          next
        when Integer
          lines << "#{define_directive} #{name} #{value}"
        when String
          lines << "#{define_directive} #{name}_#{sanitize_to_identifier(value)}"
        when Array
          emit_array_param(lines, name, value)
        end
      end
    end

    sig { params(lines: T::Array[String], name: String, value: T::Array[T.untyped]).void }
    def emit_array_param(lines, name, value)
      if value.all? { |v| v == true || v == false }
        value.each_with_index do |v, i|
          lines << "#{define_directive} #{name}_#{i}" if v
        end
      elsif value.all? { |v| v.is_a?(Integer) }
        value.uniq.sort.each do |v|
          lines << "#{define_directive} #{name}_#{v}"
        end
      elsif value.all? { |v| v.is_a?(String) }
        value.map { |v| sanitize_to_identifier(v) }.uniq.each do |sanitized|
          lines << "#{define_directive} #{name}_#{sanitized}"
        end
      end
    end
  end
end
